apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-local
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/Fierda/my_weather
    targetRevision: main
    path: k8s/local
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
